/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ProjTesteCalculadora;

import java.util.Random;

public class App {
    public String getGreeting() {
    	Random r = new Random();
    	int num = r.nextInt(4);
    	switch(num) {
    		case 0:
    			return "Bom Dia";
    			
    		case 1:
    			return "Boa Tarde";
    			
    		case 2:
    			return "Boa Noite";
    			
    		case 3:
    			return"Hey cara, como vai?";
    	}
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
